### ISSUE TITLE
Phillips Hue - Force light off?

### ISSUE THREAD

**Issue by dpgeekzero** [hollie/misterhouse#583]
@hollie I've started using your Phillips_Hue.pm and I've run into a small problem.  I will quite often use an android app to turn on one of my bulbs at an odd time, but my 'All Off' voice command in misterhouse won't turn off the bulb in this case.

Misterhouse won't turn off the bulb if it doesn't think it's on.  I'm pretty sure this is line 147-149 (haven't had time to test).

Can you explain why this is a desirable feature?  What do you think about removing the check.

**Comment by hollie** [comment]
Hello @dpgeekzero,

yes, indeed, the state of the bulb is currently stored in the MisterHouse application. This way MisterHouse can keep track of the state of the light and report it correctly in the IA7 web interface.

I only use MisterHouse to control the lights, so I never encounter the fact that the actual state of a light and the state known to MisterHouse are not in sync.

But I understand what your use case. Let me have a look on how to fix this.

A simple fix would be to send the command to the light no matter what state of the light is known to MisterHouse. You could indeed enable that by removing lines 147 - 149 from https://github.com/hollie/misterhouse/blob/stable/lib/Philips_Hue.pm#L147

I'll make a branch for that so that you can test this out.

**Comment by hollie** [comment]
Hey @dpgeekzero 

It took some time as I had some trouble installing the required HTTPS perl lib on my development machine...

Please see #586 

I've tested it and it looks OK to me. Can you test this please?

Best regards,
 Lieven.

**Comment by dpgeekzero** [comment]
I've been running with this change for the last week or two, no problems seen.

**Comment by hollie** [comment]
Hey @dpgeekzero, thanks for testing. 

I've merged the fix. Closing this ticket.
